apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
spec:
  selector:
    name: result
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002