apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result
  template:
    metadata:
      labels:
        name: result
    spec:
      containers: 
        - image: emredochub/proje206
          name: result
          ports: 
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: secret