apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web-svc
spec:
  selector:
    name: web-pod
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001