apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web-pod
  template:
    metadata:
      labels:
        name: web-pod
    spec:
      containers: 
        - image: emredochub/proje206web
          name: web-co
          ports: 
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: mysql-config
            - secretRef:
                name: secret